### ISSUE TITLE
Macro definitions not recognised during build/debug

### ISSUE THREAD

**Issue by p4-k4** [dart-lang/macros#38]
During build/debug, sometimes definitions are not recognised and/or receive an error that the "macro didn't apply properly".

This seemed somewhat difficult to reproduce however eventually found that `flutter clean && flutter pub get` then re-run `flutter/dart run --enable-experiment=macros` seems to resolve the matter.

Tested with `@JsonDecodable` macro in the json package where the `toJson` method was not being recognised.

Building/debugging for macOS (haven't tried other platforms).

`macros: ^0.1.2-main.4`

Flutter 3.24.0-1.0.pre.547 • channel master • https://github.com/flutter/flutter.git
Framework • revision 9b8470197f (3 hours ago) • 2024-08-12 03:33:05 -0400
Engine • revision 5fea110c3b
Tools • Dart 3.6.0 (build 3.6.0-134.0.dev) • DevTools 2.38.0

**Comment by davidmorgan** [comment]
Hi Paka,

Thanks for the issue report.

We are currently focused on rewriting some of the underlying macro support, so it's reasonably likely that the issue will disappear simply because we rewrite the part with the bug.

Since you don't have an exact repro it is probably not worth us digging further at this point, so I'll close; please reopen if you do find a repro, or if it's still an issue after we're through the current round of breaking changes. (Augmentation libraries -> part files, use of `dart_model` package, macro metadata in package yaml files, no more `macro` keyword).
